### ISSUE TITLE
Directories starting with a dot are not shown in file picker

### ISSUE THREAD

**Issue by cgogolin** [sheimi/SGit#243] opened 2016-08-30 11:14 UTC
I like to keep my keys in a .ssh folder and hence can not select them.

**Comment by maks** [comment] 2016-08-31 12:01
Thanks for reporting this, yes in this case it does make sense to list dot directories.

**Comment by maks** [comment] 2016-09-29 00:16
duplicate of #30

**Closed by maks** 2016-09-29 00:16 UTC
Labels: bug, duplicate
