### ISSUE TITLE
Repository on extSdCard

### ISSUE THREAD

**Issue by ondrejj** [sheimi/SGit#150] opened 2015-03-29 06:21 UTC
SGit works perfecly, but my repository is too large to store on phone's internal storage. Please, can you add ability to define storage to extSdCard? Can I define it in target repository name? I think currently "/" is not allowed in target, so I can't do it. :-(

**Comment by d10** [comment] 2015-05-17 11:56
Duplicate of #67.

**Closed by d10** 2015-05-17 11:56 UTC
