### ISSUE TITLE
http.sslVerify = false not supported in repo's config?

### ISSUE THREAD

**Issue by jds-amplify** [sheimi/SGit#45] opened 2014-01-08 17:43 UTC
Adding http.sslVerify = false to [sdcard dir]/Android/data/me.sheimi.sgit/files/repo/myrepo/.git/config causes the app to crash on opening the repo.

I manually imported a repo whose remote is an https URL, self-signed cert.

**Comment by maks** [comment] 2016-09-29 00:19
duplicate of #2

**Closed by maks** 2016-09-29 00:19 UTC
Labels: enhancement
