### ISSUE TITLE
Creating rep0 from/to another place in storage like external mem0ry card

### ISSUE THREAD

**Issue by valluminarias** [sheimi/SGit#199] opened 2016-06-20 09:51 UTC
Maybe it's nice to support creating repo from/to another place in storage like external storage, or maybe enable to locate where to save in create repo stage

**Comment by demoneaux** [comment] 2016-06-20 11:25
Hi @valluminarias! This issue is a duplicate of #13, and I think @maks is currently planning on fixing it soon. Thanks for using SGit, and feel free to open more issues if you encounter them.

**Closed by demoneaux** 2016-06-20 11:25 UTC
