### ISSUE TITLE
Client won't open on Android 6.0

### ISSUE THREAD

**Issue by scofflan** [sheimi/SGit#168] opened 2015-11-04 22:38 UTC
The application crashes on open. This issue came up after switching phones frim an HTC One M8 (Android 5.0) to a Nexus 6p ( Android 6.0). Let me know if you need more information to reproduce the issue.

**Comment by Lrs121** [comment] 2015-11-04 22:58
Duplicate.
[Issue 166](https://github.com/sheimi/SGit/issues/166)

**Comment by phcoder** [comment] 2015-11-17 15:06
Should be fixed in https://github.com/phcoder/SGit, published on https://play.google.com/store/apps/details?id=ch.phcoder.jigit. Note: I made a fork only because my pull requests went unanswered. I'm welcoming any merge back into SGit.

**Comment by Salamandar** [comment] 2015-12-03 08:44
Hum, page not fount @phcoder. And I confirm the issue.

**Comment by phcoder** [comment] 2015-12-05 09:29
@Salamandar : I had problems with Play Store anti-spam. Link should work now. Note: I renamed it to Forker and changed logo to avoid future problems with anti-spam

**Comment by maks** [comment] 2016-05-21 04:35
Duplicate of #166

**Closed by maks** 2016-05-21 04:35 UTC
Labels: duplicate
