### ISSUE TITLE
File browser does not display hidden directories

### ISSUE THREAD

**Issue by superjamie** [sheimi/SGit#250] opened 2016-08-31 21:52 UTC
If a directory is "hidden" with a dot at the start of the name, that directory does not appear in the file listing

It's common for SSH keys to be in a directory called `.ssh` so this makes it impossible to add SSH private keys in such a directory.

**Comment by maks** [comment] 2016-08-31 22:40
Duplicate of #243

**Closed by maks** 2016-08-31 22:40 UTC

**Comment by superjamie** [comment] 2016-08-31 23:01
Ahh, I did look for duplicates but I missed that one, sorry. Thank you for the quick response!
