### ISSUE TITLE
SGit editor does not allow delete the text.

### ISSUE THREAD

**Issue by s3408669** [sheimi/SGit#119] opened 2015-01-01 14:03 UTC
Steps to reproduce:
- Create a new file. 
- Click on the file to open it
- Click the edit icon on the right corner
- Type abitry text
- Delete the content

Outputs:
- Users can not delete the content using SGit editor

**Comment by d10** [comment] 2015-01-02 06:19
Duplicate of #75.

**Closed by d10** 2015-01-02 06:19 UTC
