### ISSUE TITLE
Display tracking and non-tracking local branches differently

### ISSUE THREAD

**Issue by schumaml** [sheimi/SGit#191] opened 2016-06-06 11:35 UTC
With the recent addition of "New branch", I started creating some local non-tracking branches to make edits, merge then, rinse, repeat... and get rid of them once I don't need them anymore.

Delete branch isn't there yet, but when it is, I'd like to be able to see what kind of branch I'm deleting.

**Comment by maks** [comment] 2016-06-06 11:46
Ha! Yes, very good point!
Deleting branches is very much needed, it's a very common workflow.
I'll try to get to this asap.
When you say " able to see what kind of branch I'm deleting", do you mean if it's a tracking branch?

**Comment by schumaml** [comment] 2016-06-06 12:01
Yes. In everyday workflows, the only branches I ever delete are temporary WIP branches, and being able to tell which kind a branch is would be useful.

This isn't limited to delete, of course - knowing that branch foobar1, 2, 3 are non-tracking local, and foobarBaz is tracking a remote branch, can be useful when you try to remember which one you want to work on in any case.

**Comment by maks** [comment] 2016-06-06 12:19
I've also opened a new issue for displaying tracking branch refs in the UI #192.

**Comment by maks** [comment] 2016-08-29 00:52
now that we have a separate issue #192 to for tracking branch UI this is now a duplicate of #215

**Closed by maks** 2016-08-29 00:52 UTC
Labels: enhancement
